#!/usr/bin/env bash
# =============================================================================
# setup.sh  --  Bhu-Overlay one-shot installer for Ubuntu / Linux / macOS
# =============================================================================
# Usage (from the project root):
#   chmod +x setup.sh
#   ./setup.sh
#
# What this script does:
#   1. Checks that Python 3.9+ and pip are available
#   2. Creates and activates a virtual environment  (venv/)
#   3. Installs all Python dependencies from requirements.txt
#   4. Asks which LLM provider you want (Gemini / Grok / Local)
#   5. Writes backend/.env with your settings
#   6. Starts the backend server  (Ctrl+C to stop)
#
# Re-run any time you want to change the LLM provider.
# =============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── Banner ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}=====================================================${RESET}"
echo -e "${BOLD}${CYAN}   Bhu-Overlay -- Ubuntu / Linux Installer${RESET}"
echo -e "${BOLD}${CYAN}=====================================================${RESET}"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── 1. Check Python ──────────────────────────────────────────────────────────
info "Checking Python version..."
PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        VER=$("$cmd" -c "import sys; print(sys.version_info >= (3,9))")
        if [ "$VER" = "True" ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    error "Python 3.9+ is required but not found.\n       Install it with:  sudo apt install python3 python3-pip python3-venv"
fi
success "Using $PYTHON ($($PYTHON --version))"

# ── 2. Virtual environment ───────────────────────────────────────────────────
if [ ! -d "venv" ]; then
    info "Creating virtual environment in venv/ ..."
    $PYTHON -m venv venv
    success "Virtual environment created."
else
    info "Virtual environment already exists -- skipping creation."
fi

# Activate
# shellcheck source=/dev/null
source venv/bin/activate
success "Virtual environment activated."

# ── 3. Install dependencies ──────────────────────────────────────────────────
info "Installing Python dependencies (this may take a minute)..."
pip install --upgrade pip --quiet
pip install -r requirements.txt --quiet
success "All dependencies installed."

# ── 4. Choose LLM provider ───────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Which LLM provider do you want to use for AI Kurra division?${RESET}"
echo ""
echo "  1) Google Gemini  (recommended -- free API key at https://aistudio.google.com/app/apikey)"
echo "  2) xAI Grok       (API key at https://console.x.ai/)"
echo "  3) Local LM Studio / Ollama  (no API key needed, works offline)"
echo "  4) Skip LLM setup  (fallback mode -- uses first mathematical strategy)"
echo ""
read -rp "Enter choice [1-4]: " CHOICE

ENV_FILE="backend/.env"

case "$CHOICE" in
# ─── Gemini ──────────────────────────────────────────────────────────────
1)
    echo ""
    read -rp "Paste your Gemini API key: " GEMINI_KEY
    [ -z "$GEMINI_KEY" ] && error "No API key entered."

    read -rp "Model? [Press Enter for gemini-2.5-flash]: " GEMINI_MODEL
    GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-flash}"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date)
LLM_PROVIDER=gemini
GEMINI_API_KEY=$GEMINI_KEY
GEMINI_MODEL=$GEMINI_MODEL
EOF
    success "backend/.env written."
    echo -e "     Provider : ${GREEN}gemini${RESET}"
    echo -e "     Model    : ${GREEN}$GEMINI_MODEL${RESET}"
    ;;

# ─── Grok ────────────────────────────────────────────────────────────────
2)
    echo ""
    read -rp "Paste your Grok API key: " GROK_KEY
    [ -z "$GROK_KEY" ] && error "No API key entered."

    read -rp "Model? [Press Enter for grok-2-latest]: " GROK_MODEL
    GROK_MODEL="${GROK_MODEL:-grok-2-latest}"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date)
LLM_PROVIDER=grok
GROK_API_KEY=$GROK_KEY
GROK_MODEL=$GROK_MODEL
GROK_API_URL=https://api.x.ai/v1/chat/completions
EOF
    success "backend/.env written."
    echo -e "     Provider : ${GREEN}grok${RESET}"
    echo -e "     Model    : ${GREEN}$GROK_MODEL${RESET}"
    ;;

# ─── Local ───────────────────────────────────────────────────────────────
3)
    echo ""
    warn "Make sure LM Studio or Ollama is already running before starting the backend."
    read -rp "Server URL? [Press Enter for http://localhost:1234/v1/chat/completions]: " LOCAL_URL
    LOCAL_URL="${LOCAL_URL:-http://localhost:1234/v1/chat/completions}"

    read -rp "Model name? [Press Enter for local-model]: " LOCAL_MODEL
    LOCAL_MODEL="${LOCAL_MODEL:-local-model}"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date)
LLM_PROVIDER=local
LLM_API_URL=$LOCAL_URL
LLM_MODEL_NAME=$LOCAL_MODEL
EOF
    success "backend/.env written."
    echo -e "     Provider : ${GREEN}local${RESET}"
    echo -e "     URL      : ${GREEN}$LOCAL_URL${RESET}"
    echo -e "     Model    : ${GREEN}$LOCAL_MODEL${RESET}"
    ;;

# ─── Skip ────────────────────────────────────────────────────────────────
4)
    warn "LLM setup skipped. The AI feature will use the first mathematical strategy automatically."
    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date)
# LLM skipped -- using fallback strategy
LLM_PROVIDER=local
LLM_API_URL=http://localhost:1234/v1/chat/completions
LLM_MODEL_NAME=local-model
EOF
    ;;

*)
    error "Invalid choice '$CHOICE'. Run ./setup.sh again and enter 1, 2, 3, or 4."
    ;;
esac

# ── 5. Start the backend ─────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}=====================================================${RESET}"
echo -e "${BOLD}  Setup complete!  Starting backend server...${RESET}"
echo -e "${BOLD}${CYAN}=====================================================${RESET}"
echo ""
echo -e "  Backend API : ${GREEN}http://127.0.0.1:5001${RESET}"
echo -e "  Frontend    : open ${GREEN}http://localhost:8080/frontend/index.html${RESET} in your browser"
echo ""
echo -e "  ${YELLOW}To serve the frontend, open a second terminal and run:${RESET}"
echo -e "  ${YELLOW}  source venv/bin/activate && python -m http.server 8080${RESET}"
echo ""
echo -e "  Press ${BOLD}Ctrl+C${RESET} to stop the backend."
echo ""

cd backend
python app.py
